### ISSUE TITLE
adding image="" to [section] changes font

### ISSUE THREAD

**Issue by swise23** [bizbudding/mai-pro-engine#14]
![screen shot 2017-05-19 at 2 20 34 pm](https://cloud.githubusercontent.com/assets/22770965/26261175/30280e58-3c9e-11e7-9e66-2640de9661f2.png)
![screen shot 2017-05-19 at 2 21 12 pm](https://cloud.githubusercontent.com/assets/22770965/26261176/302c815e-3c9e-11e7-8186-c014b63b3d2f.png)

**Comment by JiveDig** [comment]
Adding an image to a section adds the class of "light-content" in order to make the overlayed content visible over the image. There's def an issue when using a bg image but also displaying posts/entries. It seems the light content class is overriding the default entry CSS. I'll have to figure out a way to allow both to work while still making all of the CSS easily overridable via the actual child theme, which was the whole idea.

**Comment by JiveDig** [comment]
This is a bug, but i'm moving it to future release. I'm not sure the best way to handle, and we'll just have to hope that not many people try to use [grid] inside a [section] with a background image. If we don't have any examples like that on the demo, then I think most people won't try it for now.

**Comment by JiveDig** [comment]
This should be all fixed now. Can you confirm @swise23?

**Comment by JiveDig** [comment]
Confirmed via Slack. Fixed.
